# Generated by Django 4.2.7 on 2025-09-02 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataUpload",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time this object was created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time this object was last updated.",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Upload the data file to be imported",
                        upload_to="uploads/%Y/%m",
                        verbose_name="Data File",
                    ),
                ),
                (
                    "original_file_name",
                    models.CharField(max_length=255, verbose_name="Original File Name"),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="File Size (bytes)"
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[("odoo_export", "Odoo Export"), ("other", "Other")],
                        max_length=50,
                        verbose_name="File Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "total_records",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total Records"
                    ),
                ),
                (
                    "processed_records",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Processed Records"
                    ),
                ),
                (
                    "error_records",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Error Records"
                    ),
                ),
                (
                    "current_stage",
                    models.CharField(
                        default="pending",
                        help_text="Current processing stage",
                        max_length=50,
                        verbose_name="Current Stage",
                    ),
                ),
                (
                    "stage_progress",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Progress within current stage (0-100)",
                        verbose_name="Stage Progress (%)",
                    ),
                ),
                (
                    "total_stages",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Total number of processing stages",
                        verbose_name="Total Stages",
                    ),
                ),
                (
                    "completed_stages",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of completed stages",
                        verbose_name="Completed Stages",
                    ),
                ),
                (
                    "sheet_statistics",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Detailed statistics for each sheet type (products, purchases, sales, recipes)",
                        verbose_name="Sheet Statistics",
                    ),
                ),
                (
                    "data_quality_metrics",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Comprehensive data quality metrics for each sheet",
                        verbose_name="Data Quality Metrics",
                    ),
                ),
                (
                    "start_processing_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Start Processing At"
                    ),
                ),
                (
                    "completed_processing_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed Processing At"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Error Message"
                    ),
                ),
                (
                    "processing_log",
                    models.TextField(
                        blank=True, null=True, verbose_name="Processing Log"
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Uploaded By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Upload",
                "verbose_name_plural": "Data Uploads",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProcessingError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time this object was created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time this object was last updated.",
                        verbose_name="Updated at",
                    ),
                ),
                ("row_number", models.PositiveIntegerField(verbose_name="Row Number")),
                (
                    "column_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Column Name",
                    ),
                ),
                (
                    "error_type",
                    models.CharField(max_length=50, verbose_name="Error Type"),
                ),
                ("error_message", models.TextField(verbose_name="Error Message")),
                (
                    "raw_data",
                    models.JSONField(blank=True, null=True, verbose_name="Raw Data"),
                ),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="errors",
                        to="data_management.dataupload",
                    ),
                ),
            ],
            options={
                "verbose_name": "Processing Error",
                "verbose_name_plural": "Processing Errors",
                "ordering": ["upload", "row_number"],
            },
        ),
    ]
