# Generated by Django 4.2.7 on 2025-09-02 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("analytics", "0001_initial"),
        ("restaurant_data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcosthistory",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cost_history",
                to="restaurant_data.product",
                verbose_name="Product",
            ),
        ),
        migrations.AddField(
            model_name="productcosthistory",
            name="product_category",
            field=models.ForeignKey(
                help_text="Provide both product type (resale or dish) and cost type (raw material costs, labor costs, etc.)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_cost_history",
                to="restaurant_data.producttype",
                verbose_name="Product Type",
            ),
        ),
        migrations.AddField(
            model_name="productcosthistory",
            name="unit_of_purchase",
            field=models.ForeignKey(
                help_text="Unit of measure for the quantity ordered",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cost_history_as_purchase_unit",
                to="restaurant_data.unitofmeasure",
                verbose_name="Unit of Purchase",
            ),
        ),
        migrations.AddField(
            model_name="productcosthistory",
            name="unit_of_recipe",
            field=models.ForeignKey(
                help_text="Unit of measure used in recipes for this ingredient",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cost_history_as_recipe_unit",
                to="restaurant_data.unitofmeasure",
                verbose_name="Unit of Recipe",
            ),
        ),
        migrations.AddIndex(
            model_name="dailysummary",
            index=models.Index(fields=["date"], name="analytics_d_date_1e2cfa_idx"),
        ),
        migrations.AddIndex(
            model_name="dailysummary",
            index=models.Index(
                fields=["date", "total_sales"], name="analytics_d_date_39f4f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productcosthistory",
            index=models.Index(
                fields=["product", "-purchase_date"],
                name="analytics_p_product_90828e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productcosthistory",
            index=models.Index(
                fields=["product_category", "-purchase_date"],
                name="analytics_p_product_040e74_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productcosthistory",
            index=models.Index(
                fields=["purchase_date"], name="analytics_p_purchas_f0e526_idx"
            ),
        ),
    ]
